<script>

//*********************************************************************************************************
//method to store current tab in a hidden field
function beforeSaveSupplier()
{
	//Stock current tab in hidden form item
	var currentTabId = purchase_supplier_tabsJsTabs .activeTab.name;
	document.getElementById('current_tab').value = currentTabId;
        document.getElementById('sup_locale').disabled = '';
        document.getElementById('sup_currency').disabled = '';
	//submit form
	editForm.submit();
}

</script>

<input type="hidden" id="sup_id" name="sup_id" value="<?php echo $this->getSupplier()->getId(); ?>">
<input type="hidden" id="current_tab" name="current_tab" value="">

<div class="entry-edit">

	    <div class="entry-edit-head"> 
		    <h4 class="icon-head head-edit-form fieldset-legend">General</h4> 
	    </div>

        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Id</td>
                    <td class="input-ele"><?php echo $this->getSupplier()->getId(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Name')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_name" name="sup_name" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_name(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Vendor Tax Group'); ?><span class="required">*</span></td>
                    <td class="input-ele"><?php echo $this->getVendorGroup('sup_group_id', $this->getSupplier()->getsup_group_id()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Locale')?></td>
                    <td class="input-ele"><?php echo $this->getLocaleCombo('sup_locale', $this->getSupplier()->getsup_locale()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Currency')?></td>
                    <td class="input-ele"><?php echo $this->getCurrencyCombo('sup_currency', $this->getSupplier()->getsup_currency()); ?></td>
                </tr>
                <tr style="display:none;">
                    <td class="label"><?php echo$this->__('Tax rate')?></td>
                    <td class="input-ele"><?php echo $this->getTaxRateCombo('sup_tax_rate', $this->getSupplier()->getsup_tax_rate()); ?></td>
                    
                </tr>
                <tr style="display:none;">
                    <td class="label"><?php echo$this->__('Code')?></td>
                    <td class="input-ele"><input type="text" id="sup_code" name="sup_code" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_code(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('LST no. (Local State Tax)')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_lst_num" name="sup_lst_num" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_lst_num(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('CST no. ')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_cst_num" name="sup_cst_num" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_cst_num(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Excise Registered ')?></td>
                    <td class="input-ele"><input type="checkbox" value="1" id="sup_excise_registered" name="sup_excise_registered" onclick="javascript:removeExciseNumber(this.checked);" <?php if ($this->getSupplier()->getsup_excise_registered() == 1) { echo ' checked '; echo ' disabled=\'disabled\'';} ?> ></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Excise Registration No ')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_excise_registered_num" name="sup_excise_registered_num" style="width:400px;" disabled="disabled" value="<?php echo $this->getSupplier()->getsup_excise_registered_num(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Excise Range')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_excise_range" name="sup_excise_range" style="width:400px;" disabled="disabled" value="<?php echo $this->getSupplier()->getsup_excise_range(); ?>"></td>
                </tr>
  
                <tr>
                    <td class="label"><?php echo$this->__('Excise Division ')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_excise_division" name="sup_excise_division" style="width:400px;" disabled="disabled" value="<?php echo $this->getSupplier()->getsup_excise_division(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Main Contact')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_contact" name="sup_contact" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_contact(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Address 1')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_address1" name="sup_address1" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_address1(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Address 2')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_address2" name="sup_address2" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_address2(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Zip Code')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_zipcode" name="sup_zipcode" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_zipcode(); ?>"></td>
                </tr>
                <tr>
					<td class="label"><?php echo$this->__('City')?><span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_city" name="sup_city" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_city(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Shipping State')?><span class="required">*</span></td>
                    <td class="input-ele"><?php echo $this->getStateCombo('sup_state', $this->getSupplier()->getsup_state()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Country')?><span class="required">*</span></td>
                    <td class="input-ele"><?php echo $this->getCountryCombo('sup_country', $this->getSupplier()->getsup_country()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Phone')?><span class="required">*</span></td>
                    <td class="input-ele"><textarea class="required-entry input-text"  id="sup_tel" name="sup_tel" cols="50" rows="2"><?php echo $this->getSupplier()->getsup_tel(); ?></textarea></td>
                </tr>
                <tr>
                    <td class="label">Fax</td>
                    <td class="input-ele"><input type="text" id="sup_fax" name="sup_fax" value="<?php echo $this->getSupplier()->getsup_fax(); ?>"></td>
                </tr>
                <tr>
                    <td class="label">Email<span class="required">*</span></td>
                    <td class="input-ele"><input class="required-entry input-text" type="text" id="sup_mail" name="sup_mail" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_mail(); ?>"></td>
                </tr>

                <tr>
                    <td class="label"><?php echo$this->__('Website')?></td>
                    <td class="input-ele"><input type="text" id="sup_website" name="sup_website" style="width:400px;" value="<?php echo $this->getSupplier()->getsup_website(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Comments')?></td>
                    <td colspan="4" class="input-ele"><textarea id="sup_comments" name="sup_comments" cols="100" rows="5"><?php echo $this->getSupplier()->getsup_comments(); ?></textarea></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Supplier\'s Billing Address (Business Address)')?><span class="required">*</span></td>
                    <td colspan="4" class="input-ele"><textarea class="required-entry input-text" id="sup_billing_address" name="sup_billing_address" cols="100" rows="5"><?php echo $this->getSupplier()->getsup_billing_address(); ?></textarea></td>
                </tr>
            </table>
        </fieldset>
</div>
<script>
function removeExciseNumber(flag)
{
    if(!flag)
        {
            $('sup_excise_registered_num').value='';
            $('sup_excise_registered_num').disabled='disabled';
            $('sup_excise_range').disabled='disabled';
            //$('sup_excise_code').disabled='disabled';
            $('sup_excise_division').disabled='disabled';
              
        }
    else
        {
            $('sup_excise_registered_num').disabled='';
            $('sup_excise_range').disabled='';
            //$('sup_excise_code').disabled='';
            $('sup_excise_division').disabled='';
        }
}
</script>