<script>

//*********************************************************************************************************
//method to store current tab in a hidden field
function beforeSavePrinter()
{
	//Stock current tab in hidden form item
	var currentTabId = purchase_printer_tabsJsTabs .activeTab.name;
	document.getElementById('current_tab').value = currentTabId;

	//submit form
	editForm.submit();
}

</script>

<input type="hidden" id="prntr_id" name="prntr_id" value="<?php echo $this->getPrinter()->getId(); ?>">
<input type="hidden" id="current_tab" name="current_tab" value="">

<div class="entry-edit">

	    <div class="entry-edit-head"> 
		    <h4 class="icon-head head-edit-form fieldset-legend">General</h4> 
	    </div>

        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">Id</td>
                    <td class="input-ele"><?php echo $this->getPrinter()->getId(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Name')?></td>
                    <td class="input-ele"><input type="text" id="prntr_name" name="prntr_name" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_name(); ?>"></td>
                </tr>
       <!--        <tr>
                    <td class="label"> <? //php echo$this->__('Locale')?></td>
                    <td class="input-ele"><?//php echo $this->getLocaleCombo('prntr_locale', $this->getPrinter()->getprntr_locale()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?//php echo$this->__('Currency')?></td>
                    <td class="input-ele"><?//php echo $this->getCurrencyCombo('prntr_currency', $this->getPrinter()->getprntr_currency()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?//php echo$this->__('Tax rate')?></td>
                    <td class="input-ele"><?//php echo $this->getTaxRateCombo('prntr_tax_rate', $this->getPrinter()->getprntr_tax_rate()); ?></td>
                    
                </tr>
                <tr>
                    <td class="label"><?//php echo$this->__('Code')?></td>
                    <td class="input-ele"><input type="text" id="prntr_code" name="prntr_code" style="width:400px;" value="<?//php echo $this->getPrinter()->getprntr_code(); ?>"></td>
                </tr>  -->
                <tr>
                    <td class="label"><?php echo$this->__('Main Contact')?></td>
                    <td class="input-ele"><input type="text" id="prntr_contact" name="prntr_contact" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_contact(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Address 1')?></td>
                    <td class="input-ele"><input type="text" id="prntr_address1" name="prntr_address1" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_address1(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Address 2')?></td>
                    <td class="input-ele"><input type="text" id="prntr_address2" name="prntr_address2" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_address2(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Zip Code')?></td>
                    <td class="input-ele"><input type="text" id="prntr_zipcode" name="prntr_zipcode" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_zipcode(); ?>"></td>
                </tr>
                <tr>
					<td class="label"><?php echo$this->__('City')?></td>
                    <td class="input-ele"><input type="text" id="prntr_city" name="prntr_city" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_city(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Country')?></td>
                    <td class="input-ele"><?php echo $this->getCountryCombo('prntr_country', $this->getPrinter()->getprntr_country()); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Phone')?></td>
                    <td class="input-ele"><textarea id="prntr_tel" name="prntr_tel" cols="50" rows="2"><?php echo $this->getPrinter()->getprntr_tel(); ?></textarea></td>
                </tr>
                <tr>
                    <td class="label">Fax</td>
                    <td class="input-ele"><input type="text" id="prntr_fax" name="prntr_fax" value="<?php echo $this->getPrinter()->getprntr_fax(); ?>"></td>
                </tr>
                <tr>
                    <td class="label">Email</td>
                    <td class="input-ele"><input type="text" id="prntr_mail" name="prntr_mail" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_mail(); ?>"></td>
                </tr>

                <tr>
                    <td class="label"><?php echo$this->__('Website')?></td>
                    <td class="input-ele"><input type="text" id="prntr_website" name="prntr_website" style="width:400px;" value="<?php echo $this->getPrinter()->getprntr_website(); ?>"></td>
                </tr>
                <tr>
                    <td class="label"><?php echo$this->__('Comments')?></td>
                    <td colspan="4" class="input-ele"><textarea id="prntr_comments" name="prntr_comments" cols="100" rows="5"><?php echo $this->getPrinter()->getprntr_comments(); ?></textarea></td>
                </tr>
            </table>
        </fieldset>
</div>
