<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Supply Needs')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getUrl('Purchase/SupplyNeeds/Stats'); ?>'" class="scalable" type="button"><span><?php echo $this->__('Stats')?></span></button>
                <button onclick="createPurchaseOrder();" class="scalable" type="button"><span><?php echo $this->__('Create Purchase Order :')?></span></button>
                    <form id="frm_add_to_po" name="frm_add_to_po" method="POST" action="<?php echo Mage::helper('adminhtml')->getUrl('*/*/CreatePurchaseOrder'); ?>">
                        <input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                        <select name="sup_id" id="sup_id">
                            <option value=""></option>
                            <?php foreach($this->getSuppliersAsArray() as $supId => $supName): ?>
                                <option value="<?php echo $supId; ?>"><?php echo $supName; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <input type="hidden" name="supply_needs_log" id="supply_needs_log" />
                    </form>
            </td>
        </tr>
    </table>
</div>

<?php echo $this->getGridParentHtml() ?>
<script>persistantGrid = new persistantGridControl(SupplyNeedsGridJsObject, 'supply_needs_log', 'qty_', '');</script>

