<script>

    function AllProductDelivered()
    {
        //add product deliveries in persitant grid array
        <?php echo $this->getAllProductsDeliveredJs(); ?>

        //update fields
        persistantDeliveryGrid.restoreChanges();
    }
    
    function PrintReturnVoucherUrl() {
        var printUrl = '<?php echo $this->getUrl('Purchase/Orders/PrintVoucher'); ?>';
        if($('returnsupply_vouchers').value) {
            return printUrl + 'return/1/po_voucher_num/' + $('returnsupply_vouchers').value;
        }
        return false;
    }

    function showReturnVoucherInfo() {
        var voucherId = $('returnsupply_vouchers').value ? $('returnsupply_vouchers').value : null;
        if(!voucherId)
            return false;
        
        var voucherInfoUrl = '<?php echo $this->getUrl('Purchase/Orders/VoucherInfo'); ?>';
        window.open(voucherInfoUrl + 'po_voucher_num/' + voucherId);
    }

</script>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Create New Return'); ?></h4>
</div>
<div class="entry-edit">
    <fieldset id="my-fieldset">
        <table border="0" width="100%">
            <tr>
               <?php echo $this->getPurchaseOrderVoucherBlock('add_povoucher_id_returnsupply','returnsupply'); ?>
            </tr>
            <tr>
                <td><?php echo $this->__('Date'); ?></td>
                <td width="30">&nbsp;</td>
                <td>
                    <input type="text" id="add_sm_date" name="add_sm_date" value="<?php echo date('Y-m-d'); ?>">
                    <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" id="img_calendar_sm" />
                    <script type="text/javascript">
                        Calendar.setup({
                            inputField : 'add_sm_date',
                            ifFormat : '%Y-%m-%e',
                            button : 'img_calendar_sm',
                            align : 'Bl',
                            singleClick : true
                        });
                    </script>
                </td>
                <td rowspan="2" class="a-right">
                    <p><span>Supplier Name: <b><?php echo $this->getSupplier()->getSupName(); ?></b></span></p>
                    <p><span>Supplier EP Registered: <b><?php echo ($this->getSupplier()->getSupExciseRegistered() == 1?'YES': 'NO'); ?></b></span></p>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->__('Source warehouse'); ?></td>
                <td width="30">&nbsp;</td>
                <td><?php echo $this->getWarehousesAsCombo('add_sm_warehouse_id',$this->getOrder()->getpo_target_warehouse()); ?></td>
            </tr>
        </table>

        <p>&nbsp;</p>

        <?php echo $this->getProductDeliveryBlock(); ?>

    </fieldset>
</div>


<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Return Deliveries'); ?></h4>
</div>
<div class="entry-edit">
    <div class="grid">
        <table cellspacing="0" class="data" width="100%">
            <thead>
                <tr class="headings">
                    <th class="a-center"><?php echo $this->__('Date'); ?></th>
                    <th class="a-center"><?php echo $this->__('Product'); ?></th>
                    <th class="a-center"><?php echo $this->__('Source Warehouse'); ?></th>
                    <th class="a-center"><?php echo $this->__('Qty'); ?></th>
                    <th class="a-center"><?php echo $this->__('Description'); ?></th>
                    <th class="a-center"><?php echo $this->__('Voucher'); ?></th>
                    <th class="a-center"><?php echo $this->__('Type'); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                //Affiche les mouvements de stock
                $collection = $this->getOrder()->getReturnSupplyStockMovements();
                foreach ($collection as $item) {
                    echo '<tr>';
                    echo '<td class="a-center">' . $item->getsm_date() . '</td>';
                    echo '<td class="a-center"><a href="' . $this->getUrl('AdvancedStock/Products/Edit', array('product_id' => $item->getProduct()->getId())) . '">' . $item->getProduct()->getname() . '</a></td>';
                    echo '<td class="a-center">' . Mage::getModel('AdvancedStock/Warehouse')->load($item->getSmSourceStock())->getStockName() . '</td>';
                    echo '<td class="a-center">' . $item->getsm_qty() . '</td>';
                    echo '<td class="a-center">' . $item->getsm_description() . '</td>';
                    echo '<td class="a-center">' . Mage::getModel('Purchase/Order_PoVoucher')->load($item->getsm_povoucher_id())->getVoucherTextId() . '</td>';
                    echo '<td class="a-center">' . $item->getSmType() . '</td>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
    </div>
</div>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Vouchers'); ?></h4>
</div>
<div class="entry-edit">
    <fieldset id="my-fieldset">
        <table border="0" width="100%">
            <tr>
                <td><?php echo $this->__('Select Voucher'); ?></td>
                <td width="30">&nbsp;</td>
                <td><?php echo $this->getVouchersAsCombo('returnsupply_vouchers'); ?></td>

                <td rowspan="2" class="a-right">
                    <p><button onclick="showReturnVoucherInfo();" class="scalable a-right" type="button"><span><?php echo $this->__('Voucher Info') ?></span></button></p>
                </td>
                <td rowspan="2" class="a-right" width="100">
                    <p><button onclick="setLocation(PrintReturnVoucherUrl());" class="scalable a-right" type="button"><span><?php echo $this->__('Print Voucher') ?></span></button></p>
                </td>
            </tr>
        </table>
    </fieldset>
</div>
