<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo$this->__('Voucher Information')?></h3></td>
            <td align="right">
                <button onclick="document.getElementById('edit_form').submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>

<form id="edit_form" name="edit_form" action="<?php echo $this->getUrl('*/*/savevoucherinfo', array('po_voucher_num'=>$this->getVoucher()->getId()))?>">
<div class="entry-edit">
    
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Voucher Number'); ?></td>
                    <td class="input-ele"><?php echo $this->getVoucher()->getVoucherTextId(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Invoice Id'); ?></td>
                    <td class="input-ele">   
                        <input type="text" name="povoucher_invoice_reference_num" id="povoucher_invoice_reference_num" value="<?php echo $this->getVoucher()->getPovoucherInvoiceReferenceNum(); ?>">
                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Invoice Date'); ?></td>
                    <td class="input-ele">   
                        <input size="8" type="text" name="povoucher_invoice_date" id="povoucher_invoice_date" value="<?php echo $this->getVoucher()->getpovoucher_invoice_date(); ?>">
                        <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" id="img_calendar_sm" />
                        <script type="text/javascript">
                            Calendar.setup({
                                inputField : 'povoucher_invoice_date',
                                ifFormat : '%Y-%m-%e',
                                button : 'img_calendar_sm',
                                align : 'Bl',
                                singleClick : true
                            });
                        </script>

                    </td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Remarks'); ?></td>
                    <td class="input-ele">
                        <textarea rows="4" cols="50"  name="povoucher_remarks" id="povoucher_remarks"><?php echo $this->getVoucher()->getpovoucher_remarks(); ?></textarea>
                    </td>
                </tr>
            </table>
        </fieldset>

</div>
</form>